### ISSUE TITLE
Peer to peer code review #week 3 Day 2

### ISSUE THREAD

**Issue by tobuya** [Microverse-Fullstack-Program/Webpack-Todo-List#9]
- Good implementation of the project's requirements

 ## Changes required ♻️ 

-  Please add the functionality of the `clear all completed` button.
- Please adjust the list of an array so that the new items are rendered at the top (LIFO).

**Comment by emmiiorji** [comment]
Hi @tobuya , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

![Invalid](https://user-images.githubusercontent.com/20554583/208609922-895143da-a005-417e-8888-956516c8e503.gif)

You have submitted the wrong link for the activity `Testing To Do list: part 1`. Kindly confirm that the link is correct.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
